server:
  port: 8088
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://0.0.0.0:3307/ShopApp?useSSL=false&rserverTimezone=UTC&allowPublicKeyRetrieval=true}
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://ubuntu-server-01.local:3399/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Abc123456789@}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #chỗ này mà sửa thành drop-create thì rất nguy
        #ddl-auto: validate
        #Hibernate sẽ không tạo, sửa đổi hoặc xóa bất kỳ bảng, cột hay ràng buộc nào trong cơ sở dữ liệu
        #validate thường được sử dụng trong môi trường production
        #Nếu có sự khác biệt giữa cấu trúc cơ sở dữ liệu và các entity class
        #lỗi sẽ được hiển thị và yêu cầu sửa đổi cấu trúc cơ sở dữ liệu một cách thủ công
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_SERVER:localhost}:${KAFKA_BROKER_PORT:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #transaction-id-prefix: tx.
      properties:
        "[spring.json.type.mapping]": category:com.project.shopapp.models.Category
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      # true: để sử dụng, false: để không sử dụng
      use-redis-cache: false
      host: ${REDIS_HOST:localhost} #default to 'localhost' if not provided
      port: ${REDIS_PORT:6379} #default to '6379' if not provided

  #flyway
  flyway:
    # đường dẫn đến thư mục chứa các script flyway
    locations:
      classpath:/db/migration,classpath:/dev/db/migration
    # phiên bản baseline sẽ = 1 và không thực hiện bất kỳ thay đổi nào trong DB -> true
    baseline-on-migrate: true
    baseline-version: 0

api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30 days = 30*24*60*60
  secretKey: jiAML0fQ4KgnrsopUrFYR2Z/yxQAZ4TzzQb8obQI+oY=
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60

#// khi deploy thì nên bỏ đi
logging:
  level:
    org.springframework.security: DEBUG

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
